"""Sifirdan_temiz_kurulum

Revision ID: 1bdac221e9bf
Revises: 
Create Date: 2026-01-28 20:17:56.973159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bdac221e9bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def safe_create_table(name, *args, **kwargs):
    try:
        op.create_table(name, *args, **kwargs)
        print(f"Table {name} created")
    except Exception as e:
        print(f"Table {name} already exists or error: {e}")

def safe_create_index(name, *args, **kwargs):
    try:
        op.create_index(name, *args, **kwargs)
        print(f"Index {name} created")
    except Exception as e:
        print(f"Index {name} already exists or error: {e}")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    safe_create_table('badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('icon_url', sa.String(length=255), nullable=True),
    sa.Column('criteria_type', sa.String(length=50), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_badges_id'), 'badges', ['id'], unique=False)
    safe_create_table('campus_venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('discount_rate', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_campus_venues_id'), 'campus_venues', ['id'], unique=False)
    safe_create_index(op.f('ix_campus_venues_name'), 'campus_venues', ['name'], unique=False)
    safe_create_table('icebreaker_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_icebreaker_questions_id'), 'icebreaker_questions', ['id'], unique=False)
    safe_create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('student_document_url', sa.String(length=255), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('E', 'K', name='gender'), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('favorite_music_url', sa.String(length=255), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('ghost_mode', sa.Boolean(), nullable=True),
    sa.Column('show_way_to_everyone', sa.Boolean(), nullable=True),
    sa.Column('theme_preference', sa.String(length=20), nullable=True),
    sa.Column('language_preference', sa.String(length=10), nullable=True),
    sa.Column('data_saver_mode', sa.Boolean(), nullable=True),
    sa.Column('notify_event_reminders', sa.Boolean(), nullable=True),
    sa.Column('notify_campus_announcements', sa.Boolean(), nullable=True),
    sa.Column('notify_social', sa.Boolean(), nullable=True),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.Column('tc_no', sa.String(length=11), nullable=True),
    sa.Column('id_card_front_url', sa.String(length=255), nullable=True),
    sa.Column('id_card_back_url', sa.String(length=255), nullable=True),
    sa.Column('blue_tick_status', sa.String(length=20), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_phone_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_code', sa.String(length=6), nullable=True),
    sa.Column('phone_verification_code', sa.String(length=6), nullable=True),
    sa.Column('student_document_barcode', sa.String(length=50), nullable=True),
    sa.Column('is_student_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_users_city'), 'users', ['city'], unique=False)
    safe_create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    safe_create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    safe_create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('min_age_limit', sa.Integer(), nullable=True),
    sa.Column('max_age_limit', sa.Integer(), nullable=True),
    sa.Column('target_gender', sa.Enum('HERKES', 'SADECE_KIZLAR', 'SADECE_ERKEKLER', name='targetgender'), nullable=True),
    sa.Column('status', sa.Enum('AKTIF', 'DOLDU', 'IPTAL', 'TAMAMLANDI', name='eventstatus'), nullable=True),
    sa.Column('campus_restriction', sa.String(length=100), nullable=True),
    sa.Column('gender_restriction', sa.String(length=10), nullable=True),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('campus', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('external_url', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_events_campus'), 'events', ['campus'], unique=False)
    safe_create_index(op.f('ix_events_category'), 'events', ['category'], unique=False)
    safe_create_index(op.f('ix_events_city'), 'events', ['city'], unique=False)
    safe_create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    safe_create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    safe_create_table('login_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_login_devices_id'), 'login_devices', ['id'], unique=False)
    safe_create_table('marketplace_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_marketplace_items_category'), 'marketplace_items', ['category'], unique=False)
    safe_create_index(op.f('ix_marketplace_items_id'), 'marketplace_items', ['id'], unique=False)
    safe_create_index(op.f('ix_marketplace_items_title'), 'marketplace_items', ['title'], unique=False)
    safe_create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('receiver_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    safe_create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    safe_create_table('saved_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('card_holder', sa.String(length=100), nullable=True),
    sa.Column('last_four', sa.String(length=4), nullable=True),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('card_token', sa.String(length=255), nullable=True),
    sa.Column('card_user_key', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_saved_cards_id'), 'saved_cards', ['id'], unique=False)
    safe_create_table('support_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_support_tickets_id'), 'support_tickets', ['id'], unique=False)
    safe_create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_id', sa.String(length=50), nullable=True),
    sa.Column('conversation_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'REFUNDED', name='paymentstatus'), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    safe_create_table('user_badges',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'badge_id')
    )
    safe_create_table('activity_chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['icebreaker_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_activity_chat_logs_id'), 'activity_chat_logs', ['id'], unique=False)
    safe_create_table('event_likes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'event_id')
    )
    safe_create_table('event_live_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('transport_type', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_event_live_tracking_id'), 'event_live_tracking', ['id'], unique=False)
    safe_create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('qr_scanned', sa.Boolean(), nullable=True),
    sa.Column('check_in_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='_event_user_uc')
    )
    safe_create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    safe_create_table('user_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=True),
    sa.Column('reported_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['reported_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_user_reports_id'), 'user_reports', ['id'], unique=False)
    safe_create_table('user_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['reviewed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    safe_create_index(op.f('ix_user_reviews_id'), 'user_reviews', ['id'], unique=False)
    safe_create_table('voice_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('room_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    safe_create_index(op.f('ix_voice_rooms_id'), 'voice_rooms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_rooms_id'), table_name='voice_rooms')
    op.drop_table('voice_rooms')
    op.drop_index(op.f('ix_user_reviews_id'), table_name='user_reviews')
    op.drop_table('user_reviews')
    op.drop_index(op.f('ix_user_reports_id'), table_name='user_reports')
    op.drop_table('user_reports')
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_event_live_tracking_id'), table_name='event_live_tracking')
    op.drop_table('event_live_tracking')
    op.drop_table('event_likes')
    op.drop_index(op.f('ix_activity_chat_logs_id'), table_name='activity_chat_logs')
    op.drop_table('activity_chat_logs')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_support_tickets_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_saved_cards_id'), table_name='saved_cards')
    op.drop_table('saved_cards')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_marketplace_items_title'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_id'), table_name='marketplace_items')
    op.drop_index(op.f('ix_marketplace_items_category'), table_name='marketplace_items')
    op.drop_table('marketplace_items')
    op.drop_index(op.f('ix_login_devices_id'), table_name='login_devices')
    op.drop_table('login_devices')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index(op.f('ix_events_city'), table_name='events')
    op.drop_index(op.f('ix_events_category'), table_name='events')
    op.drop_index(op.f('ix_events_campus'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_city'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_icebreaker_questions_id'), table_name='icebreaker_questions')
    op.drop_table('icebreaker_questions')
    op.drop_index(op.f('ix_campus_venues_name'), table_name='campus_venues')
    op.drop_index(op.f('ix_campus_venues_id'), table_name='campus_venues')
    op.drop_table('campus_venues')
    op.drop_index(op.f('ix_badges_id'), table_name='badges')
    op.drop_table('badges')
    # ### end Alembic commands ###
